framework:
    default_locale: '%app.locale_default%'
    translator:
        enabled_locales: '%app.locales%'
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - '%app.locale_fallback%'
