twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    date:
        format: d F Y
        interval_format: '%%d days'
    globals:
        app_name: '%app.name%'
        app_locales: '%app.locales%'
